name = "LatentODE"
uuid = "f3e7f140-5bd8-4eb3-8a74-665183c27d94"
authors = ["Florian Mrugalla <FloMru@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
